spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/boot_security_persistent_user_data?useUnicode=true&serverTimezone=Asia/Shanghai&autoReconnect=true&useSSL=false&characterEncoding=UTF-8
    username: root
    password: Qt123456@
server:
  port: 8089
